train_dataset_path: "/scratch/ar8692/multi-view-diffusion/src/data/dataset/views_three\nmeta_svd.pkl"
eval_dataset_path: "/scratch/ar8692/multi-view-diffusion/src/data/dataset/views_three\nmeta_svd.pkl"
batch_size: 1
dataset_type: "image_folder"
exp_name: "multi_gpu"
# report_to: "tensorboard"
report_to: "wandb"
learning_rate: 1e-5
weight_decay: 0
lr_scheduler: "constant"
warmup_steps: 0.05
eval_num_examples: 5
save_every_step: 40000
eval_every_step: 500
gradient_checkpointing: True
gradient_accumulation_steps: 3
num_epoch: 10
num_frames: 7
eval_metric_names:
  - "psnr_score"
  - "clip_score"
  - "lpips_score"
num_inference_steps: 25
p_mean: 1.0
p_std: 1.6
condition_p_mean: -3
condition_p_std: 0.5